/**
 * SessionStart hook. Picks the environment file for THIS operating system and writes
 * the pointer `env-local.md` that CLAUDE.md imports.
 *
 * Why a hook and not a checked-in import line: `@` imports are unconditional, and the
 * import line lives in the versioned CLAUDE.md — so a per-OS value there would be a
 * merge conflict on every machine, forever. Doing the one branch that Claude Code
 * cannot express itself, at session start, keeps CLAUDE.md and settings.json identical
 * everywhere and needs no per-machine registration at all.
 *
 * MEASURED 2026-08-28 on Claude Code 2.1.241:
 *
 *   - SessionStart runs BEFORE the instruction files are read, and what it writes lands
 *     in the SAME session. `env-local.md` did not exist before the run; the hook created
 *     it and both its import targets reached the model, `load_reason: "include"`.
 *   - It fires on `resume` too: file deleted between two runs, restored by the resumed
 *     session. `clear` and `compact` are covered by the matcher and NOT measured — they
 *     need an interactive session.
 *   - Only `startup` is load-bearing anyway. The file persists, and this hook is
 *     idempotent, so the other matchers are self-healing rather than required.
 *
 * FAILS SILENTLY BY DEFAULT, AND THAT IS WHY THE CATCH BELOW EXISTS. Measured the same
 * day: a SessionStart hook exiting 1 with a message on stderr produced no output, no
 * warning and exit 0 from `claude -p` — Claude Code discards both. (Headless mode; the
 * interactive TUI is unverified.) So a failure here cannot be reported through the
 * process. The only channel left is the file the model actually reads.
 *
 * The dangerous case is not a missing pointer but a STALE one: a leftover env-local.md
 * naming another machine's OS loads confidently wrong rules. So on failure the pointer
 * is overwritten with prose saying so, rather than left as it was.
 *
 * env-local.md is REGENERATED every start, so nothing hand-written may live in it.
 * Machine-specific notes go in env-machine.md, which this hook creates once if it is
 * missing and never touches again. Both are un-versioned: the allowlist .gitignore
 * ignores them without needing a rule.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const BANNER =
  '<!-- Generated by hooks/select-env.mjs at session start. Do not edit: it is ' +
  'overwritten every time. Machine notes go in env-machine.md. -->\n\n'

/** Exported for the test: pure, no filesystem. */
export function envFileFor(platform) {
  if (platform === 'win32') return 'env-windows.md'
  if (platform === 'darwin') return 'env-macos.md'
  return 'env-linux.md'
}

export function render(platform, exists) {
  const target = envFileFor(platform)
  // A missing OS file must be VISIBLE, not silently absent — that is the whole failure
  // mode this file exists to close. An import of a file that is not there loads nothing
  // and says nothing, so say it in prose instead.
  const os = exists
    ? `@${target}`
    : `_No environment file for platform \`${platform}\` yet (\`${target}\` is missing).` +
      ` Treat any environment claim as unverified here._`
  return `${BANNER}${os}\n@env-machine.md\n`
}

/** The pointer written when selection itself failed. No import: nothing is trustworthy. */
export function renderFailure(message) {
  return (
    `${BANNER}_Environment selection failed: ${message}. No operating-system rules are ` +
    `loaded. The machine notes imported below still apply; anything that reads like an ` +
    `OS rule does not. Run \`node hooks/select-env.mjs\` to see the error._\n` +
    `@env-machine.md\n`
  )
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function main() {
  const pointer = join(root, 'env-local.md')
  try {
    const target = envFileFor(process.platform)
    writeFileSync(pointer, render(process.platform, existsSync(join(root, target))))

    // Best-effort and deliberately after the pointer: failing to seed this file is not
    // a reason to declare the selection broken.
    try {
      const machine = join(root, 'env-machine.md')
      if (!existsSync(machine)) {
        writeFileSync(
          machine,
          '# Environment — this machine\n\n' +
            'Not versioned, and never overwritten once it exists. Facts true of this one\n' +
            'installation: which tools are present, how they are authenticated, paths that\n' +
            'only exist here. Anything true of the operating system belongs in the shared\n' +
            `\`${target}\` instead.\n`
        )
      }
    } catch {}
  } catch (error) {
    try {
      writeFileSync(pointer, renderFailure(error.message))
    } catch {
      // Nothing can be written at all. tests/env-select.test.mjs is the only backstop
      // left, and it reports on the NEXT run, not this one.
    }
  }
  // Always 0: a non-zero exit is discarded anyway (measured), and there is no reason to
  // risk standing in the way of a session over a rules file.
  process.exit(0)
}

// Only run as a hook, not when the test imports the pure functions.
if (process.argv[1] && process.argv[1].endsWith('select-env.mjs')) main()
