/**
 * SessionStart hook. Picks the environment file for THIS operating system and writes
 * the pointer `env-local.md` that CLAUDE.md imports.
 *
 * Why a hook and not a checked-in import line: `@` imports are unconditional, and the
 * import line lives in the versioned CLAUDE.md — so a per-OS value there would be a
 * merge conflict on every machine, forever. Doing the one branch that Claude Code
 * cannot express itself, at session start, keeps CLAUDE.md and settings.json identical
 * everywhere and needs no per-machine registration at all.
 *
 * MEASURED 2026-08-28 on Claude Code 2.1.241: SessionStart runs BEFORE the instruction
 * files are read, and what it writes lands in the SAME session. `env-local.md` did not
 * exist before the run; the hook created it and both its import targets reached the
 * model, with `load_reason: "include"` in an InstructionsLoaded hook. Measured with
 * matcher `startup` only — resume/clear/compact are covered by the matcher but not
 * verified.
 *
 * env-local.md is REGENERATED every start, so nothing hand-written may live in it.
 * Machine-specific notes go in env-machine.md, which this hook creates once if it is
 * missing and never touches again. Both are un-versioned: the allowlist .gitignore
 * ignores them without needing a rule.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

/** Exported for the test: pure, no filesystem. */
export function envFileFor(platform) {
  if (platform === 'win32') return 'env-windows.md'
  if (platform === 'darwin') return 'env-macos.md'
  return 'env-linux.md'
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

export function render(platform, exists) {
  const target = envFileFor(platform)
  // A missing OS file must be VISIBLE, not silently absent — that is the whole failure
  // mode this file exists to close. An import of a file that is not there loads nothing
  // and says nothing, so say it in prose instead.
  const os = exists
    ? `@${target}`
    : `_No environment file for platform \`${platform}\` yet (\`${target}\` is missing).` +
      ` Treat any environment claim as unverified here._`
  return `<!-- Generated by hooks/select-env.mjs at session start. Do not edit: ` +
    `it is overwritten every time. Machine notes go in env-machine.md. -->\n\n` +
    `${os}\n@env-machine.md\n`
}

function main() {
  const target = envFileFor(process.platform)
  writeFileSync(
    join(root, 'env-local.md'),
    render(process.platform, existsSync(join(root, target)))
  )
  const machine = join(root, 'env-machine.md')
  if (!existsSync(machine)) {
    writeFileSync(
      machine,
      '# Environment — this machine\n\n' +
        'Not versioned, and never overwritten once it exists. Facts true of this one\n' +
        'installation: which tools are present, how they are authenticated, paths that\n' +
        'only exist here. Anything true of the operating system belongs in the shared\n' +
        `\`${target}\` instead.\n`
    )
  }
}

// Only run as a hook, not when the test imports the pure functions.
if (process.argv[1] && process.argv[1].endsWith('select-env.mjs')) main()
